FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./workspaces/frontend/package*.json ./workspaces/frontend/
COPY ./workspaces/shared/package*.json ./workspaces/shared/

RUN npm ci -w workspaces/frontend

COPY ./workspaces/frontend ./workspaces/frontend
COPY ./workspaces/shared ./workspaces/shared

ARG backend_url

ENV BACKEND_URL=${backend_url}
ENV NEXT_PUBLIC_BACKEND_URL=http://localhost:4000

EXPOSE 3000:3000