FROM mongo

WORKDIR /usr/src/app

COPY ./products.json .
COPY ./categories.json .
COPY ./uploads.json .
COPY ./docker-entrypoint.sh .

RUN ["chmod", "+x", "./docker-entrypoint.sh"]
ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["sh"]