import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Landing from "../components/Landing";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <main className="relative h-[200vh] bg-gradient-to-t from-gray-400 to-[#E7ECEE]">
        <Landing />
      </main>
    </div>
  );
};

export default Home;
